language: node_js

node_js:
  - '4'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

before_script:
  npm run lint

after_success:
  npm run cover
